<script setup lang="ts">
import type { M6ConfigKind, M6ConfigRecord } from '#/api/system/bpm/integration';
import type { ColumnOption } from '@vben/art-hooks/table';
import { computed, nextTick, onMounted, reactive, ref } from 'vue';
import { ArtTable, ArtTableHeader, ArtTablePanel, useTableColumns } from '@vben/art-hooks/table';
import { Page } from '@vben/common-ui';
import { ElButton, ElDialog, ElForm, ElFormItem, ElInput, ElInputNumber, ElMessage, ElOption, ElSelect, ElTabPane, ElTabs, ElTag } from 'element-plus';
import { listM6Configs, publishM6Config, saveM6Config } from '#/api/system/bpm/integration';

defineOptions({ name: 'SystemBpmIntegrationConfigurationWorkbench' });
const active=ref<M6ConfigKind>('systems'); const loading=ref(false); const saving=ref(false); const rows=ref<M6ConfigRecord[]>([]); const dialog=ref(false);
const definitions:Record<M6ConfigKind,{label:string;id:string;fields:Array<[string,string,'number'|'select'|'text',string?]>;columns:Array<[string,string,number?]>}>={
 systems:{label:'来源系统',id:'sourceSystemVersionId',columns:[['sourceSystemCode','系统编码'],['systemVersion','版本',90],['systemName','系统名称'],['status','状态',110]],fields:[['sourceSystemCode','系统编码','text'],['systemVersion','版本','number'],['systemName','系统名称','text'],['endpointRegistryJson','端点目录 JSON','text'],['networkPolicyJson','网络策略 JSON','text']]},
 applications:{label:'外部应用',id:'applicationId',columns:[['applicationCode','应用编码'],['sourceSystemCode','来源系统'],['scopes','授权范围'],['status','状态',110]],fields:[['sourceSystemVersionId','来源版本ID','number'],['sourceSystemCode','来源系统编码','text'],['applicationCode','应用编码','text'],['secretRef','密钥引用','text'],['scopes','Scopes','text'],['expiresAt','凭据过期时间','text'],['status','状态','select','DISABLED,ACTIVE,REVOKED']]},
 mappings:{label:'员工映射',id:'mappingId',columns:[['sourceSystemCode','来源系统'],['externalEmployeeId','外部员工ID'],['hunyuanEmployeeId','员工ID',100],['status','状态',110]],fields:[['sourceSystemCode','来源系统编码','text'],['externalEmployeeId','外部员工ID','text'],['hunyuanEmployeeId','Hunyuan员工ID','number'],['validFrom','生效时间','text'],['validUntil','失效时间','text'],['status','状态','select','ACTIVE,DISABLED']]},
 bindings:{label:'流程绑定',id:'bindingVersionId',columns:[['bindingKey','绑定编码'],['bindingVersion','版本',80],['businessType','业务类型'],['graphDefinitionVersionId','Graph版本ID',110],['priority','优先级',90],['status','状态',110]],fields:[['bindingKey','绑定编码','text'],['bindingVersion','版本','number'],['businessType','业务类型','text'],['organizationId','组织ID','number'],['scenario','场景','text'],['conditionJson','条件 JSON','text'],['priority','优先级','number'],['graphDefinitionVersionId','Graph版本ID','number']]},
 subscriptions:{label:'事件订阅',id:'subscriptionVersionId',columns:[['subscriptionKey','订阅编码'],['subscriptionVersion','版本',80],['businessType','业务类型'],['connectorKey','连接器'],['endpointOperation','操作'],['status','状态',110]],fields:[['subscriptionKey','订阅编码','text'],['subscriptionVersion','版本','number'],['sourceSystemCode','来源系统编码','text'],['businessType','业务类型','text'],['eventType','事件类型','text'],['connectorKey','连接器编码','text'],['connectorVersion','连接器版本','number'],['endpointOperation','连接器操作','text'],['signingSecretRef','签名密钥引用','text'],['retryPolicyJson','重试策略 JSON','text'],['scopes','事件 Scopes','text']]},
};
const current=computed(()=>definitions[active.value]); const form=reactive<M6ConfigRecord>({});
const columnsFactory=():ColumnOption<M6ConfigRecord>[]=>[{type:'globalIndex',label:'序号',width:70,align:'center'},...current.value.columns.map(([prop,label,width])=>({prop,label,width,minWidth:width?undefined:150,useSlot:prop==='status'})),{prop:'operation',label:'操作',width:150,fixed:'right',align:'center',useSlot:true}];
const {columns,columnChecks,resetColumns}=useTableColumns(columnsFactory); const canPublish=computed(()=>active.value==='systems'||active.value==='bindings'||active.value==='subscriptions');
async function load(){loading.value=true;try{rows.value=await listM6Configs(active.value)??[];}finally{loading.value=false;}}
async function switchTab(){resetColumns();await nextTick();void load();} function open(row?:M6ConfigRecord){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,row?JSON.parse(JSON.stringify(row)):defaults());dialog.value=true;}
function defaults(){const d:M6ConfigRecord={status:'DRAFT'};for(const [key,,type] of current.value.fields)d[key]=type==='number'&&key!=='organizationId'?1:'';if(active.value==='systems'){d.endpointRegistryJson='{}';d.networkPolicyJson='{}';}if(active.value==='bindings')d.conditionJson='{}';if(active.value==='subscriptions'){d.eventType='PROCESS_RESULT';d.retryPolicyJson='{"maxAttempts":3}';d.signingSecretRef='env:';}if(active.value==='applications')d.secretRef='env:';return d;}
async function submit(){saving.value=true;try{await saveM6Config(active.value,{...form});ElMessage.success('配置已保存');dialog.value=false;await load();}finally{saving.value=false;}}
async function publishRow(row:M6ConfigRecord){const id=Number(row[current.value.id]);await publishM6Config(active.value as 'bindings'|'subscriptions'|'systems',id);ElMessage.success('配置已发布');await load();}
onMounted(()=>void load());
</script>
<template><Page auto-content-height content-class="!p-3 h-full min-h-0 overflow-hidden"><div class="workbench"><ElTabs v-model="active" class="tabs" @tab-change="switchTab"><ElTabPane v-for="(def,key) in definitions" :key="key" :label="def.label" :name="key" /></ElTabs><ArtTablePanel class="table-panel"><ArtTableHeader v-model="columnChecks" :loading="loading" layout="refresh,size,fullscreen,columns,settings" @refresh="load"><template #left><ElButton type="primary" @click="open()">新增{{current.label}}</ElButton></template></ArtTableHeader><ArtTable :columns="columns" :data="rows" height="100%" :loading="loading"><template #status="{row}"><ElTag :type="row.status==='PUBLISHED'||row.status==='ACTIVE'?'success':row.status==='REVOKED'?'danger':'info'" effect="plain">{{row.status}}</ElTag></template><template #operation="{row}"><div class="actions"><ElButton v-if="row.status==='DRAFT'||active==='applications'||active==='mappings'" link type="primary" @click="open(row)">编辑</ElButton><ElButton v-if="canPublish&&row.status==='DRAFT'" link type="success" @click="publishRow(row)">发布</ElButton></div></template></ArtTable></ArtTablePanel></div><ElDialog v-model="dialog" :title="`${form[current.id]?'编辑':'新增'}${current.label}`" width="min(760px,96vw)" destroy-on-close><ElForm label-position="top" class="form-grid"><ElFormItem v-for="field in current.fields" :key="field[0]" :label="field[1]"><ElInputNumber v-if="field[2]==='number'" v-model="form[field[0]]" :min="field[0]==='organizationId'?0:1"/><ElSelect v-else-if="field[2]==='select'" v-model="form[field[0]]"><ElOption v-for="option in field[3]?.split(',')" :key="option" :label="option" :value="option"/></ElSelect><ElInput v-else v-model="form[field[0]]" :type="field[0].endsWith('Json')?'textarea':'text'" :rows="3" /></ElFormItem></ElForm><template #footer><ElButton @click="dialog=false">取消</ElButton><ElButton type="primary" :loading="saving" @click="submit">保存</ElButton></template></ElDialog></Page></template>
<style scoped>.workbench{display:flex;flex-direction:column;height:100%;min-height:0;gap:12px}.tabs{flex:none}.tabs :deep(.el-tabs__header){margin:0}.table-panel{flex:1;min-height:0}.actions{display:inline-flex;align-items:center;justify-content:center;gap:8px}.actions .el-button{margin:0;padding:0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 16px}.form-grid :deep(.el-select),.form-grid :deep(.el-input-number){width:100%}@media(max-width:640px){.tabs :deep(.el-tabs__nav-wrap){padding:0}.tabs :deep(.el-tabs__nav-scroll){overflow:visible}.tabs :deep(.el-tabs__nav){display:grid;width:100%;grid-template-columns:repeat(5,minmax(0,1fr));transform:none!important}.tabs :deep(.el-tabs__item){min-width:0;padding:0;font-size:12px}.form-grid{grid-template-columns:1fr}}</style>
