<script setup lang="ts">
import type { BpmBusinessObjectField } from '#/api/system/bpm'; import { computed,reactive,watch } from 'vue'; import { ElButton,ElCheckbox,ElDrawer,ElForm,ElFormItem,ElInput,ElOption,ElSelect } from 'element-plus'; import { createBusinessObjectField } from '../business-object-editor-model';
const props=defineProps<{existingKeys:string[];modelValue?:BpmBusinessObjectField;open:boolean;zone:'APPLICATION'|'LINE_ITEM'|'ROUTING'|'WORKING'}>(); const emit=defineEmits<{close:[];save:[BpmBusinessObjectField]}>(); const draft=reactive<BpmBusinessObjectField>(createBusinessObjectField());
watch(()=>[props.open,props.modelValue] as const,()=>Object.assign(draft,createBusinessObjectField(),props.modelValue?JSON.parse(JSON.stringify(props.modelValue)):{}),{immediate:true});
const typeOptions=[{value:'STRING',label:'文本'},{value:'DECIMAL',label:'小数'},{value:'INTEGER',label:'整数'},{value:'BOOLEAN',label:'是/否'},{value:'DATE',label:'日期'},{value:'DATETIME',label:'日期时间'},{value:'EMPLOYEE_ID',label:'员工'}];
const controls=computed(()=>({STRING:[{value:'INPUT',label:'单行输入'},{value:'TEXTAREA',label:'多行输入'}],DECIMAL:[{value:'NUMBER',label:'数字输入'}],INTEGER:[{value:'NUMBER',label:'数字输入'}],BOOLEAN:[{value:'SWITCH',label:'开关'},{value:'RADIO',label:'单选'}],DATE:[{value:'DATE',label:'日期选择'}],DATETIME:[{value:'DATETIME',label:'日期时间'}],EMPLOYEE_ID:[{value:'EMPLOYEE',label:'员工选择'}]}[draft.type]||[]));
function suggestKey(){if(!draft.key&&draft.label)draft.key=`field${Math.abs([...draft.label].reduce((sum,char)=>sum+char.charCodeAt(0),0))}`}
function save(){suggestKey();if(!draft.label||!draft.key||props.existingKeys.includes(draft.key))return;emit('save',JSON.parse(JSON.stringify(draft)));emit('close')}
</script>
<template><ElDrawer :model-value="open" destroy-on-close size="min(460px, 92vw)" title="字段配置" @close="emit('close')"><ElForm label-position="top"><ElFormItem label="字段名称"><ElInput v-model="draft.label" @blur="suggestKey"/></ElFormItem><ElFormItem label="字段编码"><ElInput v-model="draft.key" :disabled="Boolean(modelValue)"/><small v-if="existingKeys.includes(draft.key)" class="error">字段编码已存在</small></ElFormItem><ElFormItem label="数据类型"><ElSelect v-model="draft.type" @change="draft.presentation.control=controls[0]?.value||'INPUT'"><ElOption v-for="item in typeOptions" :key="item.value" :label="item.label" :value="item.value"/></ElSelect></ElFormItem><ElFormItem label="页面控件"><ElSelect v-model="draft.presentation.control"><ElOption v-for="item in controls" :key="item.value" :label="item.label" :value="item.value"/></ElSelect></ElFormItem><ElFormItem label="输入提示"><ElInput v-model="draft.presentation.placeholder"/></ElFormItem><ElFormItem label="单位"><ElInput v-model="draft.presentation.unit"/></ElFormItem><ElFormItem><ElCheckbox v-model="draft.required">必填</ElCheckbox><ElCheckbox v-if="zone==='ROUTING'" v-model="draft.candidateUsable">可用于审批人解析</ElCheckbox></ElFormItem></ElForm><template #footer><ElButton @click="emit('close')">取消</ElButton><ElButton type="primary" @click="save">保存字段</ElButton></template></ElDrawer></template>
<style scoped>.error{color:var(--el-color-danger)}:deep(.el-select){width:100%}</style>
