<script setup lang="ts">
import type { BpmBusinessObjectDetail,BpmBusinessObjectDraft } from '#/api/system/bpm';import { computed,onMounted,reactive,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ArtEditPage,ArtEditSection } from '@vben/art-hooks/edit';import { ElButton,ElForm,ElFormItem,ElInput,ElMessage,ElMessageBox } from 'element-plus';import { activateBpmBusinessContract,createBpmBusinessObjectVisualDraft,getBpmBusinessObjectDetail,saveBpmBusinessObjectVisualDraft,validateBpmBusinessObjectVisualDraft } from '#/api/system/bpm';import { createBusinessObjectModel } from './business-object-editor-model';import BpmBusinessKeyRuleEditor from './components/bpm-business-key-rule-editor.vue';import BpmSchemaFieldTable from './components/bpm-schema-field-table.vue';import BpmLineItemDesigner from './components/bpm-line-item-designer.vue';import BpmAttachmentRuleEditor from './components/bpm-attachment-rule-editor.vue';import BpmChangePolicyEditor from './components/bpm-change-policy-editor.vue';import BpmApplicationPreview from './components/bpm-application-preview.vue';
const route=useRoute();const router=useRouter();const existing=computed(()=>Boolean(route.query.contractKey));const saving=ref(false);const findings=ref<BpmBusinessObjectDetail['findings']>([]);const summary=ref('');const model=reactive<BpmBusinessObjectDraft>(createBusinessObjectModel());
const allKeys=computed(()=>[...model.fieldSchema,...model.routingFacts,...model.workingDataSchema,...(model.lineItemSchema?.fields||[])].map(field=>field.key).filter(Boolean));
const previewDetail=computed<BpmBusinessObjectDetail>(()=>({businessSummary:summary.value,catalogRevision:model.catalogRevision,configuration:model,contractKey:model.contractKey,contractVersion:model.contractVersion,description:model.description,findings:findings.value,lifecycleState:'DRAFT',objectName:model.objectName,referenceCount:0,schemaVersion:2}));
function replaceModel(value:BpmBusinessObjectDraft){Object.keys(model).forEach(key=>delete (model as any)[key]);Object.assign(model,JSON.parse(JSON.stringify(value)))}
onMounted(async()=>{if(!existing.value)return;const detail=await getBpmBusinessObjectDetail(String(route.query.contractKey),Number(route.query.contractVersion));if(detail.configuration)replaceModel({...detail.configuration,contractVersion:detail.contractVersion,catalogRevision:detail.catalogRevision,schemaVersion:2});summary.value=detail.businessSummary});
async function validate(){const result=await validateBpmBusinessObjectVisualDraft(model);findings.value=result.findings;summary.value=result.businessSummary;if(result.valid)ElMessage.success('业务对象校验通过');return result.valid}
async function save(){saving.value=true;try{const detail=existing.value?await saveBpmBusinessObjectVisualDraft(model):await createBpmBusinessObjectVisualDraft(model);model.contractVersion=detail.contractVersion;model.catalogRevision=detail.catalogRevision;findings.value=detail.findings;summary.value=detail.businessSummary;ElMessage.success('草稿已保存');return detail}finally{saving.value=false}}
async function validateAndActivate(){if(!await validate())return;const detail=await save();await ElMessageBox.confirm('启用后该版本只读，确认继续？','启用业务对象');await activateBpmBusinessContract({catalogRevision:detail.catalogRevision,contractKey:detail.contractKey,contractVersion:detail.contractVersion});ElMessage.success('业务对象已启用');router.back()}
</script>
<template><ArtEditPage title="业务对象配置"><template #actions><ElButton @click="router.back()">返回</ElButton><ElButton :loading="saving" type="primary" @click="save">保存草稿</ElButton><ElButton @click="validate">校验配置</ElButton><ElButton type="success" @click="validateAndActivate">校验并启用</ElButton></template><ElForm label-position="top"><ArtEditSection :index="1" title="基本信息"><div class="basic-grid"><ElFormItem label="业务对象名称"><ElInput v-model="model.objectName" maxlength="128"/></ElFormItem><ElFormItem label="业务对象编码"><ElInput v-model="model.contractKey" :disabled="existing" maxlength="128"/></ElFormItem><ElFormItem label="业务类型"><ElInput v-model="model.businessType" maxlength="64"/></ElFormItem><ElFormItem class="full" label="使用说明"><ElInput v-model="model.description" maxlength="500" type="textarea"/></ElFormItem></div></ArtEditSection><ArtEditSection :index="2" title="业务编号"><BpmBusinessKeyRuleEditor v-model="model.businessKeyRule"/></ArtEditSection><ArtEditSection :index="3" title="申请字段"><BpmSchemaFieldTable v-model="model.fieldSchema" :all-keys="allKeys" title="申请人填写的字段" zone="APPLICATION"/></ArtEditSection><ArtEditSection :index="4" title="流程路由字段"><BpmSchemaFieldTable v-model="model.routingFacts" :all-keys="allKeys" title="用于决定审批人的字段" zone="ROUTING"/></ArtEditSection><ArtEditSection :index="5" title="审批过程字段"><BpmSchemaFieldTable v-model="model.workingDataSchema" :all-keys="allKeys" title="审批过程中记录的字段" zone="WORKING"/></ArtEditSection><ArtEditSection :index="6" title="明细行"><BpmLineItemDesigner v-model="model.lineItemSchema" :all-keys="allKeys"/></ArtEditSection><ArtEditSection :index="7" title="附件要求"><BpmAttachmentRuleEditor v-model="model.attachmentRule"/></ArtEditSection><ArtEditSection :index="8" title="审批修改规则"><BpmChangePolicyEditor v-model="model.dataChangeRule" :working-fields="model.workingDataSchema"/></ArtEditSection><ArtEditSection :index="9" title="实际表单预览"><BpmApplicationPreview :detail="previewDetail"/></ArtEditSection><ArtEditSection v-if="summary||findings.length" :index="10" title="校验结果"><p>{{summary}}</p><div v-for="finding in findings" :key="`${finding.code}-${finding.fieldPath}`" class="finding"><strong>{{finding.message}}</strong><span>{{finding.suggestion}}</span></div></ArtEditSection></ElForm></ArtEditPage></template>
<style scoped>.basic-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0 16px}.full{grid-column:1/-1}.finding{display:grid;gap:4px;margin-top:8px;padding:10px;border-left:3px solid var(--el-color-danger);background:var(--el-color-danger-light-9)}.finding span{color:var(--el-text-color-secondary)}@media(max-width:760px){.basic-grid{grid-template-columns:1fr}.full{grid-column:auto}}</style>
