<script setup lang="ts">
import type { BpmDefinitionReference,BpmPolicyBusinessDetail,BpmPolicyType } from '#/api/system/bpm/policy';
import { computed,onMounted,ref } from 'vue'; import { useRoute,useRouter } from 'vue-router'; import { useAccess } from '@vben/access'; import { Page } from '@vben/common-ui'; import { ElButton,ElDescriptions,ElDescriptionsItem,ElEmpty,ElTag } from 'element-plus';
import { exportBpmPolicyTechnicalDetail,getBpmPolicyCatalogVersion,queryBpmPolicyReferences } from '#/api/system/bpm/policy'; import BpmTechnicalPolicyPanel from './components/bpm-technical-policy-panel.vue';
const route=useRoute();const router=useRouter();const detail=ref<BpmPolicyBusinessDetail>();const references=ref<BpmDefinitionReference[]>([]);const {hasAccessByCodes}=useAccess();const canViewTechnical=computed(()=>hasAccessByCodes(['bpm:policy-catalog:technical']));
onMounted(async()=>{detail.value=await getBpmPolicyCatalogVersion({type:route.query.type as BpmPolicyType,policyKey:String(route.query.policyKey),policyVersion:Number(route.query.policyVersion)});references.value=await queryBpmPolicyReferences(detail.value.reference)});
async function exportProtocol(){if(!detail.value)return;const content=await exportBpmPolicyTechnicalDetail(detail.value.reference) as Blob;const url=URL.createObjectURL(content);const link=document.createElement('a');link.href=url;link.download=`${detail.value.reference.policyKey}-v${detail.value.reference.policyVersion}.json`;link.click();URL.revokeObjectURL(url)}
</script>
<template><Page><header class="page-header"><ElButton @click="router.back()">返回</ElButton><ElButton v-if="canViewTechnical" @click="exportProtocol">导出协议</ElButton></header><template v-if="detail"><ElDescriptions :column="1" border><ElDescriptionsItem label="规则名称">{{detail.policyName}}</ElDescriptionsItem><ElDescriptionsItem label="规则编码">{{detail.reference.policyKey}}</ElDescriptionsItem><ElDescriptionsItem label="版本">v{{detail.reference.policyVersion}}</ElDescriptionsItem><ElDescriptionsItem label="状态"><ElTag>{{detail.lifecycleState}}</ElTag></ElDescriptionsItem><ElDescriptionsItem label="业务摘要">{{detail.businessSummary}}</ElDescriptionsItem><ElDescriptionsItem label="风险">{{detail.calculatedRiskLevel}}</ElDescriptionsItem><ElDescriptionsItem label="Graph 引用"><div v-if="references.length"><ElTag v-for="item in references" :key="`${item.referenceSource}-${item.graphDefinitionVersionId||item.draftId}`" class="mr-2">{{item.processName}} {{item.referenceSource==='DRAFT'?'草稿':'v'+item.definitionVersion}}</ElTag></div><span v-else>暂无引用</span></ElDescriptionsItem></ElDescriptions><section v-if="canViewTechnical" class="technical"><BpmTechnicalPolicyPanel :reference="detail.reference"/></section></template><ElEmpty v-else description="正在加载"/></Page></template>
<style scoped>.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.technical{margin-top:16px}</style>
