<script setup lang="ts">
import type { BpmPolicyBusinessValidationResult, BpmPolicyType, BpmPolicyVisualDraft } from '#/api/system/bpm/policy';
import { computed, onMounted, reactive, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router';
import { ArtEditPage, ArtEditSection } from '@vben/art-hooks/edit';
import { ElButton,ElForm,ElFormItem,ElInput,ElMessage,ElMessageBox } from 'element-plus';
import { activateBpmPolicyVersion,activateHighRiskBpmPolicyVersion,createBpmPolicyVisualDraft,getBpmPolicyCatalogVersion,saveBpmPolicyVisualDraft,validateBpmPolicyVisualDraft } from '#/api/system/bpm/policy';
import { createPolicyModel,toPolicyVisualSaveParams } from './policy-editor-model';
import BpmRuleTypeSelector from './components/bpm-rule-type-selector.vue'; import BpmCandidateRuleEditor from './components/bpm-candidate-rule-editor.vue'; import BpmApprovalRuleEditor from './components/bpm-approval-rule-editor.vue'; import BpmScopeBuilder from './components/bpm-scope-builder.vue'; import BpmRuleSummary from './components/bpm-rule-summary.vue'; import BpmRuleSimulationPanel from './components/bpm-rule-simulation-panel.vue';
const route=useRoute(); const router=useRouter(); const existing=computed(()=>Boolean(route.query.policyKey)); const saving=ref(false); const validation=ref<BpmPolicyBusinessValidationResult>(); const model=reactive<BpmPolicyVisualDraft>(createPolicyModel((route.query.type as BpmPolicyType)||'CANDIDATE'));
function replaceModel(value:BpmPolicyVisualDraft){Object.keys(model).forEach((key)=>delete (model as any)[key]);Object.assign(model,value)}
function changeType(type:BpmPolicyType){if(!existing.value)replaceModel(createPolicyModel(type))}
watch(()=>model.type,(type,previous)=>{if(type!==previous)changeType(type)});
onMounted(async()=>{if(!existing.value)return;const detail=await getBpmPolicyCatalogVersion({type:route.query.type as BpmPolicyType,policyKey:String(route.query.policyKey),policyVersion:Number(route.query.policyVersion)});if(detail.configuration)replaceModel({...detail.configuration,policyVersion:detail.reference.policyVersion,catalogRevision:detail.catalogRevision});});
async function validate(){validation.value=await validateBpmPolicyVisualDraft(toPolicyVisualSaveParams(model)); if(validation.value.valid)ElMessage.success('规则校验通过');}
async function save(){saving.value=true;try{const detail=existing.value?await saveBpmPolicyVisualDraft(toPolicyVisualSaveParams(model)):await createBpmPolicyVisualDraft(toPolicyVisualSaveParams(model));model.policyVersion=detail.reference.policyVersion;model.catalogRevision=detail.catalogRevision;ElMessage.success('草稿已保存');return detail;}finally{saving.value=false}}
async function validateAndActivate(){await validate();if(!validation.value?.valid)return;const detail=await save();const params={...detail.reference,catalogRevision:detail.catalogRevision};if(validation.value.calculatedRiskLevel==='HIGH'){const {value}=await ElMessageBox.prompt('该规则为高风险，请填写启用理由。','高风险启用确认',{inputValidator:(text)=>Boolean(text?.trim())||'请输入确认理由',type:'warning'});await activateHighRiskBpmPolicyVersion({...params,confirmationReason:value});}else{await ElMessageBox.confirm('启用后该版本只读，确认继续？','启用规则');await activateBpmPolicyVersion(params);}ElMessage.success('规则已启用');router.back();}
</script>
<template><ArtEditPage title="审批规则配置"><template #actions><ElButton @click="router.back()">返回</ElButton><ElButton :loading="saving" type="primary" @click="save">保存草稿</ElButton><ElButton @click="validate">校验规则</ElButton><ElButton type="success" @click="validateAndActivate">校验并启用</ElButton></template><div class="editor-layout"><ElForm label-position="top"><ArtEditSection :index="1" title="基本信息"><ElFormItem label="规则类型"><BpmRuleTypeSelector v-model="model.type" :disabled="existing"/></ElFormItem><ElFormItem label="规则名称"><ElInput v-model="model.policyName" maxlength="128"/></ElFormItem><ElFormItem label="规则编码"><ElInput v-model="model.policyKey" :disabled="existing" maxlength="128"/></ElFormItem><ElFormItem label="使用说明"><ElInput v-model="model.description" maxlength="500" type="textarea"/></ElFormItem></ArtEditSection><ArtEditSection :index="2" title="业务配置"><BpmCandidateRuleEditor v-if="model.candidate" v-model="model.candidate"/><BpmApprovalRuleEditor v-if="model.approval" v-model="model.approval"/><template v-if="model.startVisibility"><BpmScopeBuilder v-model="model.startVisibility.startScope" label="谁可以发起"/><BpmScopeBuilder v-model="model.startVisibility.visibilityScope" label="谁可以查看"/></template></ArtEditSection><ArtEditSection v-if="model.type==='CANDIDATE'" :index="3" title="规则模拟"><BpmRuleSimulationPanel :draft="model"/></ArtEditSection></ElForm><aside><BpmRuleSummary :risk="validation?.calculatedRiskLevel" :summary="validation?.businessSummary"/><div v-for="finding in validation?.findings" :key="finding.code" class="finding"><strong>{{finding.message}}</strong><span>{{finding.suggestion}}</span></div></aside></div></ArtEditPage></template>
<style scoped>.editor-layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:16px}.finding{display:grid;gap:4px;margin-top:12px;padding:12px;border-left:3px solid var(--el-color-danger);background:var(--el-color-danger-light-9)}.finding span{color:var(--el-text-color-secondary)}@media(max-width:900px){.editor-layout{grid-template-columns:1fr}}</style>
