CREATE TABLE `t_bpm_category` (
  `category_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_code` varchar(64) NOT NULL COMMENT '分类编码',
  `category_name` varchar(128) NOT NULL COMMENT '分类名称',
  `icon` varchar(255) DEFAULT NULL COMMENT '图标',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `disabled_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否禁用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`category_id`) USING BTREE,
  UNIQUE KEY `uk_category_code` (`category_code`) USING BTREE,
  KEY `idx_category_enabled_sort` (`disabled_flag`, `sort`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程分类';

CREATE TABLE `t_bpm_form` (
  `form_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `form_key` varchar(64) NOT NULL COMMENT '表单编码',
  `form_name` varchar(128) NOT NULL COMMENT '表单名称',
  `schema_json` longtext NOT NULL COMMENT '表单 schema',
  `layout_json` longtext DEFAULT NULL COMMENT '表单布局',
  `disabled_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否禁用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`form_id`) USING BTREE,
  UNIQUE KEY `uk_form_key` (`form_key`) USING BTREE,
  KEY `idx_form_name` (`form_name`) USING BTREE,
  KEY `idx_form_enabled` (`disabled_flag`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程表单';

CREATE TABLE `t_bpm_model` (
  `model_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `model_key` varchar(64) NOT NULL COMMENT '模型编码',
  `model_name` varchar(128) NOT NULL COMMENT '模型名称',
  `category_id` bigint NOT NULL COMMENT '分类ID',
  `form_type` tinyint NOT NULL COMMENT '表单类型',
  `form_id` bigint NOT NULL COMMENT '表单ID',
  `visible_flag` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可见',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  `simple_model_json` longtext NOT NULL COMMENT '设计器草稿 JSON',
  `start_rule_json` longtext NOT NULL COMMENT '发起规则 JSON',
  `manager_scope_json` longtext DEFAULT NULL COMMENT '主管范围 JSON',
  `title_rule_json` longtext DEFAULT NULL COMMENT '标题规则 JSON',
  `summary_rule_json` longtext DEFAULT NULL COMMENT '摘要规则 JSON',
  `variable_mapping_json` longtext DEFAULT NULL COMMENT '变量映射 JSON',
  `instance_no_rule_id` int DEFAULT NULL COMMENT '单号规则 ID',
  `published_definition_id` bigint DEFAULT NULL COMMENT '已发布定义 ID',
  `has_unpublished_changes` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否存在未发布变更',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`model_id`) USING BTREE,
  UNIQUE KEY `uk_model_key` (`model_key`) USING BTREE,
  KEY `idx_model_category` (`category_id`) USING BTREE,
  KEY `idx_model_form` (`form_id`) USING BTREE,
  KEY `idx_model_published` (`published_definition_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程模型草稿';

CREATE TABLE `t_bpm_definition` (
  `definition_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `model_id` bigint NOT NULL COMMENT '模型ID',
  `definition_key` varchar(64) NOT NULL COMMENT '定义编码',
  `definition_name` varchar(128) NOT NULL COMMENT '定义名称',
  `definition_version` int NOT NULL COMMENT '定义版本',
  `category_id_snapshot` bigint NOT NULL COMMENT '分类快照ID',
  `category_name_snapshot` varchar(128) NOT NULL COMMENT '分类名称快照',
  `form_type_snapshot` tinyint NOT NULL COMMENT '表单类型快照',
  `form_id_snapshot` bigint NOT NULL COMMENT '表单ID快照',
  `form_name_snapshot` varchar(128) NOT NULL COMMENT '表单名称快照',
  `form_schema_snapshot_json` longtext NOT NULL COMMENT '表单 schema 快照',
  `simple_model_snapshot_json` longtext NOT NULL COMMENT '设计器草稿快照',
  `compiled_bpmn_xml` longtext NOT NULL COMMENT '编译后的 BPMN XML',
  `start_rule_snapshot_json` longtext NOT NULL COMMENT '发起规则快照',
  `manager_scope_snapshot_json` longtext DEFAULT NULL COMMENT '主管范围快照',
  `title_rule_snapshot_json` longtext DEFAULT NULL COMMENT '标题规则快照',
  `summary_rule_snapshot_json` longtext DEFAULT NULL COMMENT '摘要规则快照',
  `variable_mapping_snapshot_json` longtext DEFAULT NULL COMMENT '变量映射快照',
  `instance_no_rule_id_snapshot` int DEFAULT NULL COMMENT '单号规则快照',
  `lifecycle_state` tinyint NOT NULL COMMENT '生命周期状态',
  `start_state` tinyint NOT NULL COMMENT '发起状态',
  `engine_process_definition_id` varchar(128) NOT NULL COMMENT '引擎定义ID',
  `published_by_employee_id` bigint NOT NULL COMMENT '发布员工ID',
  `published_by_name_snapshot` varchar(64) NOT NULL COMMENT '发布员工姓名快照',
  `published_at` datetime NOT NULL COMMENT '发布时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`definition_id`) USING BTREE,
  UNIQUE KEY `uk_definition_key_version` (`definition_key`, `definition_version`) USING BTREE,
  KEY `idx_definition_model` (`model_id`) USING BTREE,
  KEY `idx_definition_engine` (`engine_process_definition_id`) USING BTREE,
  KEY `idx_definition_current` (`definition_key`, `lifecycle_state`, `start_state`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程定义发布快照';

CREATE TABLE `t_bpm_definition_node` (
  `definition_node_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `definition_id` bigint NOT NULL COMMENT '定义ID',
  `node_key` varchar(128) NOT NULL COMMENT '节点编码',
  `node_type` varchar(32) NOT NULL COMMENT '节点类型',
  `node_name_snapshot` varchar(128) DEFAULT NULL COMMENT '节点名称快照',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `authored_rule_snapshot_json` longtext NOT NULL COMMENT '设计规则快照',
  `compiled_node_snapshot_json` longtext NOT NULL COMMENT '编译结果快照',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`definition_node_id`) USING BTREE,
  UNIQUE KEY `uk_definition_node` (`definition_id`, `node_key`) USING BTREE,
  KEY `idx_definition_node_sort` (`definition_id`, `sort_order`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程定义节点快照';

CREATE TABLE `t_bpm_instance` (
  `instance_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `instance_no` varchar(64) NOT NULL COMMENT '实例编号',
  `definition_id` bigint NOT NULL COMMENT '定义ID',
  `engine_process_definition_id` varchar(128) NOT NULL COMMENT '引擎定义ID',
  `engine_process_instance_id` varchar(128) NOT NULL COMMENT '引擎实例ID',
  `definition_key_snapshot` varchar(64) NOT NULL COMMENT '定义编码快照',
  `definition_version_snapshot` int NOT NULL COMMENT '定义版本快照',
  `category_id_snapshot` bigint NOT NULL COMMENT '分类ID快照',
  `category_name_snapshot` varchar(128) NOT NULL COMMENT '分类名称快照',
  `title` varchar(256) NOT NULL COMMENT '实例标题',
  `summary` varchar(1000) DEFAULT NULL COMMENT '实例摘要',
  `start_employee_id` bigint NOT NULL COMMENT '发起员工ID',
  `start_employee_name_snapshot` varchar(64) NOT NULL COMMENT '发起员工姓名快照',
  `start_department_id_snapshot` bigint DEFAULT NULL COMMENT '发起部门ID快照',
  `start_department_name_snapshot` varchar(128) DEFAULT NULL COMMENT '发起部门名称快照',
  `business_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `business_id` bigint DEFAULT NULL COMMENT '业务ID',
  `business_key` varchar(128) DEFAULT NULL COMMENT '业务键',
  `initial_form_data_snapshot_json` longtext NOT NULL COMMENT '首次表单快照',
  `current_form_data_snapshot_json` longtext NOT NULL COMMENT '当前表单快照',
  `run_state` tinyint NOT NULL COMMENT '运行状态',
  `result_state` tinyint DEFAULT NULL COMMENT '结果状态',
  `active_task_count` int NOT NULL DEFAULT 0 COMMENT '活动任务数',
  `current_node_summary_json` longtext DEFAULT NULL COMMENT '当前节点摘要',
  `cancel_by_employee_id` bigint DEFAULT NULL COMMENT '取消员工ID',
  `cancel_by_name_snapshot` varchar(64) DEFAULT NULL COMMENT '取消员工姓名快照',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `started_at` datetime NOT NULL COMMENT '发起时间',
  `last_action_at` datetime NOT NULL COMMENT '最后动作时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `cancelled_at` datetime DEFAULT NULL COMMENT '取消时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`instance_id`) USING BTREE,
  UNIQUE KEY `uk_instance_no` (`instance_no`) USING BTREE,
  KEY `idx_instance_definition` (`definition_id`) USING BTREE,
  KEY `idx_instance_start` (`start_employee_id`, `run_state`) USING BTREE,
  KEY `idx_instance_business` (`business_type`, `business_id`) USING BTREE,
  KEY `idx_instance_engine` (`engine_process_instance_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程实例投影';

CREATE TABLE `t_bpm_task` (
  `task_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `instance_id` bigint NOT NULL COMMENT '实例ID',
  `definition_id` bigint NOT NULL COMMENT '定义ID',
  `definition_node_id` bigint NOT NULL COMMENT '定义节点ID',
  `engine_task_id` varchar(128) NOT NULL COMMENT '引擎任务ID',
  `engine_execution_id` varchar(128) DEFAULT NULL COMMENT '引擎执行ID',
  `engine_process_instance_id` varchar(128) NOT NULL COMMENT '引擎实例ID',
  `task_key` varchar(128) NOT NULL COMMENT '任务编码',
  `task_name` varchar(128) NOT NULL COMMENT '任务名称',
  `instance_no` varchar(64) NOT NULL COMMENT '实例编号',
  `instance_title` varchar(256) NOT NULL COMMENT '实例标题',
  `start_employee_id` bigint NOT NULL COMMENT '发起员工ID',
  `start_employee_name_snapshot` varchar(64) NOT NULL COMMENT '发起员工姓名快照',
  `category_id_snapshot` bigint NOT NULL COMMENT '分类ID快照',
  `category_name_snapshot` varchar(128) NOT NULL COMMENT '分类名称快照',
  `assignee_employee_id` bigint DEFAULT NULL COMMENT '当前处理员工ID',
  `assignee_name_snapshot` varchar(64) DEFAULT NULL COMMENT '当前处理员工姓名快照',
  `assignee_department_id_snapshot` bigint DEFAULT NULL COMMENT '当前处理部门ID快照',
  `assignee_department_name_snapshot` varchar(128) DEFAULT NULL COMMENT '当前处理部门名称快照',
  `runtime_assignment_snapshot_json` longtext DEFAULT NULL COMMENT '运行时分配快照',
  `task_state` tinyint NOT NULL COMMENT '任务状态',
  `task_result` tinyint DEFAULT NULL COMMENT '任务结果',
  `assigned_at` datetime NOT NULL COMMENT '分配时间',
  `due_at` datetime DEFAULT NULL COMMENT '截止时间',
  `completed_at` datetime DEFAULT NULL COMMENT '完成时间',
  `cancelled_at` datetime DEFAULT NULL COMMENT '取消时间',
  `last_action_at` datetime NOT NULL COMMENT '最后动作时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`task_id`) USING BTREE,
  UNIQUE KEY `uk_engine_task` (`engine_task_id`) USING BTREE,
  KEY `idx_task_instance` (`instance_id`) USING BTREE,
  KEY `idx_task_assignee` (`assignee_employee_id`, `task_state`) USING BTREE,
  KEY `idx_task_node` (`definition_node_id`) USING BTREE,
  KEY `idx_task_assigned` (`assigned_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程任务投影';

CREATE TABLE `t_bpm_task_action_log` (
  `action_log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `instance_id` bigint NOT NULL COMMENT '实例ID',
  `task_id` bigint DEFAULT NULL COMMENT '任务ID',
  `definition_id` bigint NOT NULL COMMENT '定义ID',
  `definition_node_id` bigint DEFAULT NULL COMMENT '定义节点ID',
  `engine_task_id` varchar(128) DEFAULT NULL COMMENT '引擎任务ID',
  `action_type` varchar(32) NOT NULL COMMENT '动作类型',
  `actor_employee_id` bigint NOT NULL COMMENT '动作员工ID',
  `actor_name_snapshot` varchar(64) NOT NULL COMMENT '动作员工姓名快照',
  `from_assignee_employee_id` bigint DEFAULT NULL COMMENT '原处理员工ID',
  `to_assignee_employee_id` bigint DEFAULT NULL COMMENT '目标处理员工ID',
  `comment_text` varchar(2000) DEFAULT NULL COMMENT '审批意见',
  `action_payload_json` longtext DEFAULT NULL COMMENT '动作负载',
  `action_at` datetime NOT NULL COMMENT '动作时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`action_log_id`) USING BTREE,
  KEY `idx_log_instance` (`instance_id`, `action_at`) USING BTREE,
  KEY `idx_log_task` (`task_id`, `action_at`) USING BTREE,
  KEY `idx_log_actor` (`actor_employee_id`, `action_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程任务动作日志';

CREATE TABLE `t_bpm_instance_copy` (
  `copy_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `instance_id` bigint NOT NULL COMMENT '实例ID',
  `definition_id` bigint NOT NULL COMMENT '定义ID',
  `definition_node_id` bigint DEFAULT NULL COMMENT '定义节点ID',
  `engine_process_instance_id` varchar(128) NOT NULL COMMENT '引擎实例ID',
  `source_node_key` varchar(128) NOT NULL COMMENT '来源节点编码',
  `source_node_name` varchar(128) DEFAULT NULL COMMENT '来源节点名称',
  `target_employee_id` bigint NOT NULL COMMENT '抄送目标员工ID',
  `target_name_snapshot` varchar(64) NOT NULL COMMENT '抄送目标姓名快照',
  `copy_type` varchar(32) NOT NULL COMMENT '抄送类型',
  `read_state` tinyint NOT NULL DEFAULT 0 COMMENT '已读状态',
  `channel_snapshot_json` longtext DEFAULT NULL COMMENT '通知渠道快照',
  `reason_snapshot` varchar(500) DEFAULT NULL COMMENT '抄送原因快照',
  `sent_at` datetime NOT NULL COMMENT '发送时间',
  `read_at` datetime DEFAULT NULL COMMENT '阅读时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`copy_id`) USING BTREE,
  KEY `idx_copy_target` (`target_employee_id`, `read_state`, `sent_at`) USING BTREE,
  KEY `idx_copy_instance` (`instance_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程抄送投影';

-- BPM 管理端菜单与页面路由
INSERT INTO `t_menu` (`menu_id`, `menu_name`, `menu_type`, `parent_id`, `sort`, `path`, `component`, `perms_type`, `icon`, `visible_flag`, `disabled_flag`, `deleted_flag`, `create_user_id`, `create_time`, `update_time`)
VALUES
  (308, '流程引擎', 1, 0, 40, '/system/bpm', NULL, 1, 'ep:connection', 1, 0, 0, 1, now(), now()),
  (309, '流程分类', 2, 308, 1, '/system/bpm/category', '/system/bpm/category/category-list.vue', 1, 'ep:collection-tag', 1, 0, 0, 1, now(), now()),
  (310, '流程表单', 2, 308, 2, '/system/bpm/form', '/system/bpm/form/form-list.vue', 1, 'ep:document', 1, 0, 0, 1, now(), now()),
  (311, '流程模型', 2, 308, 3, '/system/bpm/model', '/system/bpm/model/model-list.vue', 1, 'ep:share', 1, 0, 0, 1, now(), now()),
  (312, '流程定义', 2, 308, 4, '/system/bpm/definition', '/system/bpm/definition/definition-list.vue', 1, 'ep:files', 1, 0, 0, 1, now(), now()),
  (313, '流程实例', 2, 308, 5, '/system/bpm/instance', '/system/bpm/instance/instance-list.vue', 1, 'ep:histogram', 1, 0, 0, 1, now(), now()),
  (314, '流程任务', 2, 308, 6, '/system/bpm/task', '/system/bpm/task/task-list.vue', 1, 'ep:list', 1, 0, 0, 1, now(), now()),
  (315, '流程监听器', 2, 308, 7, '/system/bpm/listener', '/system/bpm/listener/listener-catalog.vue', 1, 'ep:bell', 1, 0, 0, 1, now(), now());
