-- BPM 枚举与 M1 建模运行字典。允许在已人工补录部分字典的环境重复执行。
INSERT INTO `t_dict` (`dict_name`, `dict_code`, `remark`, `disabled_flag`)
SELECT source.`dict_name`, source.`dict_code`, source.`remark`, 0
FROM (
    SELECT 'BPM流程定义版本状态' dict_name, 'BPM_DEFINITION_LIFECYCLE_STATE' dict_code, 'BPM定义版本生命周期' remark
    UNION ALL SELECT 'BPM流程定义发起状态', 'BPM_DEFINITION_START_STATE', 'BPM定义是否允许发起'
    UNION ALL SELECT 'BPM表单类型', 'BPM_FORM_TYPE', '流程模型绑定的表单来源'
    UNION ALL SELECT 'BPM实例运行状态', 'BPM_INSTANCE_RUN_STATE', 'BPM实例当前运行阶段'
    UNION ALL SELECT 'BPM实例结果状态', 'BPM_INSTANCE_RESULT_STATE', 'BPM实例终态结果'
    UNION ALL SELECT 'BPM任务状态', 'BPM_TASK_STATE', 'BPM人工任务处理状态'
    UNION ALL SELECT 'BPM任务结果', 'BPM_TASK_RESULT', 'BPM人工任务处理结果'
    UNION ALL SELECT 'BPM任务类型', 'BPM_TASK_KIND', '审批或办理任务'
    UNION ALL SELECT 'BPM任务动作', 'BPM_TASK_ACTION', '员工端可执行任务动作'
    UNION ALL SELECT 'BPM任务操作日志类型', 'BPM_TASK_ACTION_LOG_TYPE', '流程任务与实例操作事实类型'
    UNION ALL SELECT 'BPM候选人解析类型', 'BPM_CANDIDATE_RESOLVER_TYPE', '发布与运行期候选人来源'
    UNION ALL SELECT 'BPM审批模式', 'BPM_APPROVAL_MODE', '单人、顺签或会签模式'
    UNION ALL SELECT 'BPM字段权限', 'BPM_FIELD_PERMISSION', '节点表单字段权限'
    UNION ALL SELECT 'BPM抄送读取状态', 'BPM_COPY_READ_STATE', '员工抄送读取状态'
    UNION ALL SELECT 'BPM抄送类型', 'BPM_COPY_TYPE', '手工或设计时抄送来源'
    UNION ALL SELECT 'BPM通知渠道', 'BPM_NOTIFICATION_CHANNEL', '流程通知发送渠道'
    UNION ALL SELECT 'BPM通知发送状态', 'BPM_NOTIFICATION_SEND_STATUS', '流程通知发送结果'
    UNION ALL SELECT 'BPM回调状态', 'BPM_CALLBACK_STATUS', '可靠业务回调状态'
    UNION ALL SELECT 'BPM业务命令类型', 'BPM_COMMAND_TYPE', '业务接入命令类型'
    UNION ALL SELECT 'BPM业务命令状态', 'BPM_COMMAND_STATUS', '业务接入命令执行状态'
    UNION ALL SELECT 'BPM审批组状态', 'BPM_APPROVAL_GROUP_STATE', '顺序或并行审批组状态'
    UNION ALL SELECT 'BPM审批组关闭原因', 'BPM_APPROVAL_GROUP_CLOSE_REASON', '审批组终止原因'
    UNION ALL SELECT 'BPM表单数据变更来源', 'BPM_FORM_DATA_CHANGE_SOURCE', '审批数据版本变更来源'
    UNION ALL SELECT 'BPM流程节点类型', 'BPM_PROCESS_NODE_TYPE', 'M1受控AST节点类型'
    UNION ALL SELECT 'BPM分支类型', 'BPM_BRANCH_TYPE', 'M1受控分支类型'
    UNION ALL SELECT 'BPM运行节点状态', 'BPM_RUNTIME_NODE_STATE', 'authored运行图节点状态'
    UNION ALL SELECT 'BPM路由计算状态', 'BPM_ROUTE_EVALUATION_STATUS', '结构化路由决定计算状态'
    UNION ALL SELECT 'BPM样板费用审批状态', 'BPM_SAMPLE_EXPENSE_APPROVAL_STATUS', '样板费用业务审批状态'
) source
WHERE NOT EXISTS (
    SELECT 1 FROM `t_dict` existing WHERE existing.`dict_code` = source.`dict_code`
);

INSERT INTO `t_dict_data`
(`dict_id`, `data_value`, `data_label`, `remark`, `sort_order`, `disabled_flag`)
SELECT dict.`dict_id`, source.`data_value`, source.`data_label`, source.`enum_key`, source.`sort_order`, 0
FROM (
    SELECT 'BPM_DEFINITION_LIFECYCLE_STATE' dict_code, '1' data_value, '当前版本' data_label, 'CURRENT' enum_key, 100 sort_order
    UNION ALL SELECT 'BPM_DEFINITION_LIFECYCLE_STATE', '2', '历史版本', 'HISTORICAL', 90
    UNION ALL SELECT 'BPM_DEFINITION_START_STATE', '1', '可发起', 'STARTABLE', 100
    UNION ALL SELECT 'BPM_DEFINITION_START_STATE', '2', '已停用', 'SUSPENDED', 90
    UNION ALL SELECT 'BPM_FORM_TYPE', '1', '内置表单', 'BUILT_IN', 100
    UNION ALL SELECT 'BPM_INSTANCE_RUN_STATE', '1', '流转中', 'RUNNING', 100
    UNION ALL SELECT 'BPM_INSTANCE_RUN_STATE', '2', '待重新提交', 'WAIT_RESUBMIT', 90
    UNION ALL SELECT 'BPM_INSTANCE_RUN_STATE', '3', '已结束', 'FINISHED', 80
    UNION ALL SELECT 'BPM_INSTANCE_RUN_STATE', '4', '已取消', 'CANCELLED', 70
    UNION ALL SELECT 'BPM_INSTANCE_RESULT_STATE', '1', '审批通过', 'APPROVED', 100
    UNION ALL SELECT 'BPM_INSTANCE_RESULT_STATE', '2', '审批拒绝', 'REJECTED', 90
    UNION ALL SELECT 'BPM_INSTANCE_RESULT_STATE', '3', '发起人取消', 'CANCELLED_BY_START_USER', 80
    UNION ALL SELECT 'BPM_INSTANCE_RESULT_STATE', '4', '管理员取消', 'CANCELLED_BY_ADMIN', 70
    UNION ALL SELECT 'BPM_TASK_STATE', '1', '待处理', 'PENDING', 100
    UNION ALL SELECT 'BPM_TASK_STATE', '2', '已完成', 'COMPLETED', 90
    UNION ALL SELECT 'BPM_TASK_STATE', '3', '已取消', 'CANCELLED', 80
    UNION ALL SELECT 'BPM_TASK_RESULT', '1', '审批通过', 'APPROVED', 100
    UNION ALL SELECT 'BPM_TASK_RESULT', '2', '审批拒绝', 'REJECTED', 90
    UNION ALL SELECT 'BPM_TASK_RESULT', '3', '退回发起人', 'RETURNED', 80
    UNION ALL SELECT 'BPM_TASK_RESULT', '4', '实例已取消', 'INSTANCE_CANCELLED', 70
    UNION ALL SELECT 'BPM_TASK_RESULT', '5', '加签已减签', 'ADD_SIGN_REDUCED', 60
    UNION ALL SELECT 'BPM_TASK_RESULT', '6', '发起人撤回', 'RECALLED', 50
    UNION ALL SELECT 'BPM_TASK_RESULT', '7', '办理完成', 'HANDLED', 40
    UNION ALL SELECT 'BPM_TASK_KIND', 'APPROVAL', '审批任务', 'APPROVAL', 100
    UNION ALL SELECT 'BPM_TASK_KIND', 'HANDLE', '办理任务', 'HANDLE', 90
    UNION ALL SELECT 'BPM_TASK_ACTION', 'APPROVE', '通过', 'APPROVE', 100
    UNION ALL SELECT 'BPM_TASK_ACTION', 'REJECT', '拒绝', 'REJECT', 90
    UNION ALL SELECT 'BPM_TASK_ACTION', 'COMPLETE', '完成', 'COMPLETE', 80
    UNION ALL SELECT 'BPM_TASK_ACTION', 'RETURN', '退回', 'RETURN', 70
    UNION ALL SELECT 'BPM_TASK_ACTION', 'TRANSFER', '转办', 'TRANSFER', 60
    UNION ALL SELECT 'BPM_TASK_ACTION', 'DELEGATE', '委派', 'DELEGATE', 50
    UNION ALL SELECT 'BPM_TASK_ACTION', 'ADD_SIGN', '加签', 'ADD_SIGN', 40
    UNION ALL SELECT 'BPM_TASK_ACTION', 'REDUCE_SIGN', '减签', 'REDUCE_SIGN', 30
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'APPROVED', '审批通过', 'APPROVED', 160
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'REJECTED', '审批拒绝', 'REJECTED', 150
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'RETURNED_TO_INITIATOR', '退回发起人', 'RETURNED_TO_INITIATOR', 140
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'TRANSFERRED', '转办', 'TRANSFERRED', 130
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'ADMIN_TRANSFERRED', '管理员转办', 'ADMIN_TRANSFERRED', 120
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'ADD_SIGNED', '加签', 'ADD_SIGNED', 110
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'REDUCE_SIGNED', '减签', 'REDUCE_SIGNED', 100
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'RECALLED', '发起人撤回', 'RECALLED', 90
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'DELEGATED', '委派', 'DELEGATED', 80
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'HANDLE_COMPLETED', '办理完成', 'HANDLE_COMPLETED', 70
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'PARALLEL_MEMBER_APPROVED', '并行成员通过', 'PARALLEL_MEMBER_APPROVED', 60
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'PARALLEL_MEMBER_REJECTED', '并行成员拒绝', 'PARALLEL_MEMBER_REJECTED', 50
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'PARALLEL_MEMBER_RETURNED', '并行成员退回', 'PARALLEL_MEMBER_RETURNED', 40
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'INSTANCE_CANCELLED', '发起人取消实例', 'INSTANCE_CANCELLED', 30
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'ADMIN_INSTANCE_CANCELLED', '管理员取消实例', 'ADMIN_INSTANCE_CANCELLED', 20
    UNION ALL SELECT 'BPM_TASK_ACTION_LOG_TYPE', 'RESUBMITTED', '发起人重新提交', 'RESUBMITTED', 10
    UNION ALL SELECT 'BPM_CANDIDATE_RESOLVER_TYPE', 'EMPLOYEE', '指定员工', 'EMPLOYEE', 100
    UNION ALL SELECT 'BPM_CANDIDATE_RESOLVER_TYPE', 'DEPARTMENT_MANAGER', '部门主管', 'DEPARTMENT_MANAGER', 90
    UNION ALL SELECT 'BPM_CANDIDATE_RESOLVER_TYPE', 'ROLE', '角色成员', 'ROLE', 80
    UNION ALL SELECT 'BPM_CANDIDATE_RESOLVER_TYPE', 'START_EMPLOYEE', '发起人本人', 'START_EMPLOYEE', 70
    UNION ALL SELECT 'BPM_CANDIDATE_RESOLVER_TYPE', 'START_DEPARTMENT_MANAGER', '发起人部门主管', 'START_DEPARTMENT_MANAGER', 60
    UNION ALL SELECT 'BPM_CANDIDATE_RESOLVER_TYPE', 'EMPLOYEE_SELECT_AT_START', '发起时自选审批人', 'EMPLOYEE_SELECT_AT_START', 50
    UNION ALL SELECT 'BPM_APPROVAL_MODE', 'single', '单人审批', 'SINGLE', 100
    UNION ALL SELECT 'BPM_APPROVAL_MODE', 'singleOnly', '单人审批且仅限一人', 'SINGLE_ONLY', 90
    UNION ALL SELECT 'BPM_APPROVAL_MODE', 'sequential', '顺序会签', 'SEQUENTIAL', 80
    UNION ALL SELECT 'BPM_APPROVAL_MODE', 'parallelAll', '并行会签', 'PARALLEL_ALL', 70
    UNION ALL SELECT 'BPM_FIELD_PERMISSION', 'READONLY', '只读', 'READONLY', 100
    UNION ALL SELECT 'BPM_FIELD_PERMISSION', 'EDITABLE', '可编辑', 'EDITABLE', 90
    UNION ALL SELECT 'BPM_FIELD_PERMISSION', 'HIDDEN', '隐藏', 'HIDDEN', 80
    UNION ALL SELECT 'BPM_COPY_READ_STATE', '0', '未读', 'UNREAD', 100
    UNION ALL SELECT 'BPM_COPY_READ_STATE', '1', '已读', 'READ', 90
    UNION ALL SELECT 'BPM_COPY_TYPE', 'MANUAL_APPROVE_COPY', '审批通过手工抄送', 'MANUAL_APPROVE_COPY', 100
    UNION ALL SELECT 'BPM_COPY_TYPE', 'MANUAL_REJECT_COPY', '审批拒绝手工抄送', 'MANUAL_REJECT_COPY', 90
    UNION ALL SELECT 'BPM_COPY_TYPE', 'MANUAL_RETURN_COPY', '退回发起人手工抄送', 'MANUAL_RETURN_COPY', 80
    UNION ALL SELECT 'BPM_COPY_TYPE', 'DESIGN_NODE_COPY', '设计时抄送节点', 'DESIGN_NODE_COPY', 70
    UNION ALL SELECT 'BPM_NOTIFICATION_CHANNEL', 'MESSAGE', '站内信', 'MESSAGE', 100
    UNION ALL SELECT 'BPM_NOTIFICATION_CHANNEL', 'SMS', '短信', 'SMS', 90
    UNION ALL SELECT 'BPM_NOTIFICATION_CHANNEL', 'MAIL', '邮件', 'MAIL', 80
    UNION ALL SELECT 'BPM_NOTIFICATION_SEND_STATUS', '0', '待发送', 'PENDING', 100
    UNION ALL SELECT 'BPM_NOTIFICATION_SEND_STATUS', '1', '发送成功', 'SUCCESS', 90
    UNION ALL SELECT 'BPM_NOTIFICATION_SEND_STATUS', '2', '发送失败', 'FAIL', 80
    UNION ALL SELECT 'BPM_CALLBACK_STATUS', '0', '待处理', 'PENDING', 100
    UNION ALL SELECT 'BPM_CALLBACK_STATUS', '1', '成功', 'SUCCEEDED', 90
    UNION ALL SELECT 'BPM_CALLBACK_STATUS', '2', '失败', 'FAILED', 80
    UNION ALL SELECT 'BPM_CALLBACK_STATUS', '3', '需人工补偿', 'NEEDS_COMPENSATION', 70
    UNION ALL SELECT 'BPM_CALLBACK_STATUS', '4', '已补偿', 'COMPENSATED', 60
    UNION ALL SELECT 'BPM_COMMAND_TYPE', 'START', '发起流程', 'START', 100
    UNION ALL SELECT 'BPM_COMMAND_STATUS', '0', '处理中', 'PENDING', 100
    UNION ALL SELECT 'BPM_COMMAND_STATUS', '1', '成功', 'SUCCEEDED', 90
    UNION ALL SELECT 'BPM_COMMAND_STATUS', '2', '失败', 'FAILED', 80
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_STATE', 'PENDING', '待处理', 'PENDING', 100
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_STATE', 'APPROVED', '已通过', 'APPROVED', 90
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_STATE', 'REJECTED', '已拒绝', 'REJECTED', 80
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_STATE', 'RETURNED', '已退回', 'RETURNED', 70
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_STATE', 'CANCELLED', '已取消', 'CANCELLED', 60
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_CLOSE_REASON', 'ALL_APPROVED', '全部通过', 'ALL_APPROVED', 100
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_CLOSE_REASON', 'MEMBER_REJECTED', '成员拒绝', 'MEMBER_REJECTED', 90
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_CLOSE_REASON', 'MEMBER_RETURNED', '成员退回', 'MEMBER_RETURNED', 80
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_CLOSE_REASON', 'INSTANCE_RECALLED', '实例撤回', 'INSTANCE_RECALLED', 70
    UNION ALL SELECT 'BPM_APPROVAL_GROUP_CLOSE_REASON', 'INSTANCE_CANCELLED', '实例取消', 'INSTANCE_CANCELLED', 60
    UNION ALL SELECT 'BPM_FORM_DATA_CHANGE_SOURCE', 'INSTANCE_STARTED', '实例发起', 'INSTANCE_STARTED', 100
    UNION ALL SELECT 'BPM_FORM_DATA_CHANGE_SOURCE', 'TASK_APPROVED', '任务审批', 'TASK_APPROVED', 90
    UNION ALL SELECT 'BPM_FORM_DATA_CHANGE_SOURCE', 'INSTANCE_RESUBMITTED', '实例重提', 'INSTANCE_RESUBMITTED', 80
    UNION ALL SELECT 'BPM_PROCESS_NODE_TYPE', 'USER_TASK', '审批节点', 'USER_TASK', 100
    UNION ALL SELECT 'BPM_PROCESS_NODE_TYPE', 'HANDLE_TASK', '办理节点', 'HANDLE_TASK', 90
    UNION ALL SELECT 'BPM_PROCESS_NODE_TYPE', 'COPY_TASK', '抄送节点', 'COPY_TASK', 80
    UNION ALL SELECT 'BPM_PROCESS_NODE_TYPE', 'EXCLUSIVE_BRANCH', '排他分支', 'EXCLUSIVE_BRANCH', 70
    UNION ALL SELECT 'BPM_PROCESS_NODE_TYPE', 'PARALLEL_BRANCH', '并行分支', 'PARALLEL_BRANCH', 60
    UNION ALL SELECT 'BPM_PROCESS_NODE_TYPE', 'INCLUSIVE_BRANCH', '包容分支', 'INCLUSIVE_BRANCH', 50
    UNION ALL SELECT 'BPM_BRANCH_TYPE', 'EXCLUSIVE', '排他', 'EXCLUSIVE', 100
    UNION ALL SELECT 'BPM_BRANCH_TYPE', 'PARALLEL', '并行', 'PARALLEL', 90
    UNION ALL SELECT 'BPM_BRANCH_TYPE', 'INCLUSIVE', '包容', 'INCLUSIVE', 80
    UNION ALL SELECT 'BPM_RUNTIME_NODE_STATE', 'NOT_ENTERED', '未进入', 'NOT_ENTERED', 100
    UNION ALL SELECT 'BPM_RUNTIME_NODE_STATE', 'ACTIVE', '处理中', 'ACTIVE', 90
    UNION ALL SELECT 'BPM_RUNTIME_NODE_STATE', 'COMPLETED', '已完成', 'COMPLETED', 80
    UNION ALL SELECT 'BPM_RUNTIME_NODE_STATE', 'CANCELLED', '已取消', 'CANCELLED', 70
    UNION ALL SELECT 'BPM_RUNTIME_NODE_STATE', 'SKIPPED', '已跳过', 'SKIPPED', 60
    UNION ALL SELECT 'BPM_ROUTE_EVALUATION_STATUS', 'SUCCEEDED', '计算成功', 'SUCCEEDED', 100
    UNION ALL SELECT 'BPM_ROUTE_EVALUATION_STATUS', 'FAILED', '计算失败', 'FAILED', 90
    UNION ALL SELECT 'BPM_SAMPLE_EXPENSE_APPROVAL_STATUS', '0', '草稿', 'DRAFT', 100
    UNION ALL SELECT 'BPM_SAMPLE_EXPENSE_APPROVAL_STATUS', '1', '审批中', 'APPROVING', 90
    UNION ALL SELECT 'BPM_SAMPLE_EXPENSE_APPROVAL_STATUS', '2', '已通过', 'APPROVED', 80
    UNION ALL SELECT 'BPM_SAMPLE_EXPENSE_APPROVAL_STATUS', '3', '已拒绝', 'REJECTED', 70
) source
JOIN `t_dict` dict ON dict.`dict_code` = source.`dict_code`
LEFT JOIN `t_dict_data` existing
  ON existing.`dict_id` = dict.`dict_id`
 AND existing.`data_value` = source.`data_value`
WHERE existing.`dict_data_id` IS NULL;
