-- BPM M6：配置化业务接入控制面、开放身份和可靠事件订阅。
-- 执行前提：已执行 v3.55.0（M3 审批对象）至 v3.57.0（M5 高级运行）。
-- 兼容影响：仅新增控制面表并扩展回调投递事实；旧内部回调的订阅字段保持 NULL。
-- 恢复方式：停用外部应用并确认无 M6 配置/投递数据后，删除菜单权限、回调扩展列和新增表。
CREATE TABLE IF NOT EXISTS `t_bpm_source_system_version` (`source_system_version_id` bigint NOT NULL AUTO_INCREMENT,`source_system_code` varchar(64) NOT NULL,`system_version` int NOT NULL,`system_name` varchar(128) NOT NULL,`endpoint_registry_json` longtext NOT NULL,`network_policy_json` longtext NOT NULL,`status` varchar(32) NOT NULL,`published_at` datetime NULL,`create_time` datetime NOT NULL,`update_time` datetime NOT NULL,PRIMARY KEY (`source_system_version_id`),UNIQUE KEY `uk_bpm_source_system_version` (`source_system_code`,`system_version`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `t_bpm_source_application` (`application_id` bigint NOT NULL AUTO_INCREMENT,`source_system_version_id` bigint NOT NULL,`source_system_code` varchar(64) NOT NULL,`application_code` varchar(64) NOT NULL,`secret_ref` varchar(256) NOT NULL,`scopes` varchar(1000) NOT NULL,`status` varchar(32) NOT NULL,`expires_at` datetime NULL,`create_time` datetime NOT NULL,`update_time` datetime NOT NULL,PRIMARY KEY (`application_id`),UNIQUE KEY `uk_bpm_source_application` (`application_code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `t_bpm_external_request_nonce` (`nonce_id` bigint NOT NULL AUTO_INCREMENT,`application_id` bigint NOT NULL,`nonce_value` varchar(128) NOT NULL,`expires_at` datetime NOT NULL,`create_time` datetime NOT NULL,PRIMARY KEY (`nonce_id`),UNIQUE KEY `uk_bpm_external_nonce` (`application_id`,`nonce_value`),KEY `idx_bpm_external_nonce_expiry` (`expires_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `t_bpm_external_employee_mapping` (`mapping_id` bigint NOT NULL AUTO_INCREMENT,`source_system_code` varchar(64) NOT NULL,`external_employee_id` varchar(128) NOT NULL,`hunyuan_employee_id` bigint NOT NULL,`status` varchar(32) NOT NULL,`valid_from` datetime NULL,`valid_until` datetime NULL,`create_time` datetime NOT NULL,`update_time` datetime NOT NULL,PRIMARY KEY (`mapping_id`),UNIQUE KEY `uk_bpm_external_employee` (`source_system_code`,`external_employee_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `t_bpm_external_public_reference` (`public_reference_id` bigint NOT NULL AUTO_INCREMENT,`public_id` varchar(64) NOT NULL,`source_system_code` varchar(64) NOT NULL,`object_type` varchar(32) NOT NULL,`internal_id` bigint NOT NULL,`create_time` datetime NOT NULL,PRIMARY KEY (`public_reference_id`),UNIQUE KEY `uk_bpm_external_public_id` (`public_id`),UNIQUE KEY `uk_bpm_external_public_object` (`source_system_code`,`object_type`,`internal_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `t_bpm_process_binding_version` (`binding_version_id` bigint NOT NULL AUTO_INCREMENT,`binding_key` varchar(128) NOT NULL,`binding_version` int NOT NULL,`business_type` varchar(128) NOT NULL,`organization_id` bigint NULL,`scenario` varchar(64) NULL,`condition_json` longtext NOT NULL,`priority` int NOT NULL,`graph_definition_version_id` bigint NOT NULL,`status` varchar(32) NOT NULL,`effective_from` datetime NULL,`effective_until` datetime NULL,`published_at` datetime NULL,`create_time` datetime NOT NULL,`update_time` datetime NOT NULL,PRIMARY KEY (`binding_version_id`),UNIQUE KEY `uk_bpm_process_binding_version` (`binding_key`,`binding_version`),KEY `idx_bpm_process_binding_match` (`business_type`,`organization_id`,`scenario`,`status`,`priority`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `t_bpm_event_subscription_version` (`subscription_version_id` bigint NOT NULL AUTO_INCREMENT,`subscription_key` varchar(128) NOT NULL,`subscription_version` int NOT NULL,`source_system_code` varchar(64) NOT NULL,`business_type` varchar(128) NOT NULL,`event_type` varchar(64) NOT NULL,`connector_key` varchar(128) NOT NULL,`connector_version` int NOT NULL,`endpoint_operation` varchar(128) NOT NULL,`signing_secret_ref` varchar(256) NOT NULL,`retry_policy_json` longtext NOT NULL,`scopes` varchar(1000) NULL,`status` varchar(32) NOT NULL,`published_at` datetime NULL,`create_time` datetime NOT NULL,`update_time` datetime NOT NULL,PRIMARY KEY (`subscription_version_id`),UNIQUE KEY `uk_bpm_event_subscription_version` (`subscription_key`,`subscription_version`),KEY `idx_bpm_event_subscription_match` (`business_type`,`event_type`,`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `t_bpm_callback_record` MODIFY COLUMN `business_id` bigint NULL COMMENT '兼容旧业务数字ID';
SET @m6_business_key_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND column_name='business_key')=1,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD COLUMN `business_key` varchar(256) NULL AFTER `business_id`'); PREPARE m6_business_key_stmt FROM @m6_business_key_sql; EXECUTE m6_business_key_stmt; DEALLOCATE PREPARE m6_business_key_stmt;
SET @m6_subscription_id_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND column_name='subscription_version_id')=1,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD COLUMN `subscription_version_id` bigint NULL AFTER `event_id`'); PREPARE m6_subscription_id_stmt FROM @m6_subscription_id_sql; EXECUTE m6_subscription_id_stmt; DEALLOCATE PREPARE m6_subscription_id_stmt;
SET @m6_connector_key_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND column_name='connector_key')=1,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD COLUMN `connector_key` varchar(128) NULL AFTER `subscription_version_id`'); PREPARE m6_connector_key_stmt FROM @m6_connector_key_sql; EXECUTE m6_connector_key_stmt; DEALLOCATE PREPARE m6_connector_key_stmt;
SET @m6_connector_version_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND column_name='connector_version')=1,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD COLUMN `connector_version` int NULL AFTER `connector_key`'); PREPARE m6_connector_version_stmt FROM @m6_connector_version_sql; EXECUTE m6_connector_version_stmt; DEALLOCATE PREPARE m6_connector_version_stmt;
SET @m6_endpoint_operation_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND column_name='endpoint_operation')=1,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD COLUMN `endpoint_operation` varchar(128) NULL AFTER `connector_version`'); PREPARE m6_endpoint_operation_stmt FROM @m6_endpoint_operation_sql; EXECUTE m6_endpoint_operation_stmt; DEALLOCATE PREPARE m6_endpoint_operation_stmt;
SET @m6_signing_secret_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND column_name='signing_secret_ref')=1,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD COLUMN `signing_secret_ref` varchar(256) NULL AFTER `endpoint_operation`'); PREPARE m6_signing_secret_stmt FROM @m6_signing_secret_sql; EXECUTE m6_signing_secret_stmt; DEALLOCATE PREPARE m6_signing_secret_stmt;
SET @m6_retry_policy_sql=IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND column_name='retry_policy_json')=1,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD COLUMN `retry_policy_json` longtext NULL AFTER `signing_secret_ref`'); PREPARE m6_retry_policy_stmt FROM @m6_retry_policy_sql; EXECUTE m6_retry_policy_stmt; DEALLOCATE PREPARE m6_retry_policy_stmt;
SET @m6_business_key_index_sql=IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND index_name='idx_bpm_callback_business_key')>0,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD KEY `idx_bpm_callback_business_key` (`business_type`,`business_key`)'); PREPARE m6_business_key_index_stmt FROM @m6_business_key_index_sql; EXECUTE m6_business_key_index_stmt; DEALLOCATE PREPARE m6_business_key_index_stmt;
SET @m6_callback_unique_sql = IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='t_bpm_callback_record' AND index_name='uk_bpm_callback_event_subscription')>0,'SELECT 1','ALTER TABLE `t_bpm_callback_record` ADD UNIQUE KEY `uk_bpm_callback_event_subscription` (`event_id`,`subscription_version_id`)');
PREPARE m6_callback_unique_stmt FROM @m6_callback_unique_sql; EXECUTE m6_callback_unique_stmt; DEALLOCATE PREPARE m6_callback_unique_stmt;
INSERT INTO `t_menu` (`menu_id`,`menu_name`,`menu_type`,`parent_id`,`sort`,`path`,`component`,`perms_type`,`api_perms`,`web_perms`,`icon`,`frame_flag`,`cache_flag`,`visible_flag`,`disabled_flag`,`deleted_flag`,`create_user_id`,`create_time`,`update_time`) VALUES
(371,'业务接入配置',2,308,23,'/system/bpm/integration/configuration-workbench','/system/bpm/integration/configuration-workbench.vue',1,NULL,NULL,'ep:connection',0,0,1,0,0,1,now(),now()),
(372,'查询业务接入配置',3,371,1,NULL,NULL,1,'bpm:integration-config:query','bpm:integration-config:query',NULL,0,0,1,0,0,1,now(),now()),
(373,'维护业务接入配置',3,371,2,NULL,NULL,1,'bpm:integration-config:update','bpm:integration-config:update',NULL,0,0,1,0,0,1,now(),now()),
(374,'发布业务接入配置',3,371,3,NULL,NULL,1,'bpm:integration-config:publish','bpm:integration-config:publish',NULL,0,0,1,0,0,1,now(),now()) ON DUPLICATE KEY UPDATE `menu_name`=VALUES(`menu_name`),`component`=VALUES(`component`),`api_perms`=VALUES(`api_perms`),`web_perms`=VALUES(`web_perms`),`update_time`=now();
INSERT INTO `t_role_menu` (`role_id`,`menu_id`,`create_time`,`update_time`) SELECT 1,m.menu_id,now(),now() FROM t_menu m WHERE m.menu_id IN (371,372,373,374) AND NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id=1 AND rm.menu_id=m.menu_id);
