package com.hunyuan.sa.bpm.module.businesscontract.service;

import com.alibaba.fastjson.JSON;
import com.hunyuan.sa.bpm.module.businesscontract.domain.visual.*;
import com.hunyuan.sa.bpm.module.candidate.service.PolicyCanonicalizer;
import org.apache.commons.lang3.StringUtils;
import java.util.*;

public class BusinessObjectV2DocumentMapper {
 private static final Set<String> TYPES=Set.of("STRING","DECIMAL","INTEGER","BOOLEAN","DATE","DATETIME","EMPLOYEE_ID");
 private static final Map<String,Set<String>> CONTROLS=Map.of(
  "STRING",Set.of("INPUT","TEXTAREA","SELECT"),"DECIMAL",Set.of("NUMBER"),"INTEGER",Set.of("NUMBER"),
  "BOOLEAN",Set.of("SWITCH","RADIO"),"DATE",Set.of("DATE"),"DATETIME",Set.of("DATETIME"),"EMPLOYEE_ID",Set.of("EMPLOYEE"));
 private final PolicyCanonicalizer canonicalizer=new PolicyCanonicalizer(); private final BusinessObjectBusinessSummaryService summaryService=new BusinessObjectBusinessSummaryService();

 public BusinessObjectValidationResult compile(BpmBusinessObjectDraft draft){List<BusinessObjectValidationFinding> findings=new ArrayList<>();validate(draft,findings);Map<String,Object> document=build(draft);String canonical=canonicalizer.canonicalize(JSON.toJSONString(document));return new BusinessObjectValidationResult(findings.isEmpty(),canonical,canonicalizer.sha256(canonical),summaryService.summarize(draft),List.copyOf(findings));}
 public BusinessObjectValidationResult validateCanonical(String canonical){try{var object=JSON.parseObject(canonical);if(object==null||object.getIntValue("schemaVersion")!=2)throw new IllegalArgumentException("缺少 schemaVersion=2");return new BusinessObjectValidationResult(true,canonicalizer.canonicalize(canonical),canonicalizer.sha256(canonicalizer.canonicalize(canonical)),"Schema v2 业务对象",List.of());}catch(RuntimeException ex){return new BusinessObjectValidationResult(false,"","","",List.of(new BusinessObjectValidationFinding("INVALID_V2","BLOCKING","document",ex.getMessage(),"请检查业务对象配置")));}}
 public BpmBusinessObjectDraft restore(String contractKey,String objectName,String description,long revision,String canonical){var d=JSON.parseObject(canonical);if(d==null||d.getIntValue("schemaVersion")!=2)return null;return new BpmBusinessObjectDraft(contractKey,objectName,description,d.getString("sourceSystem"),d.getString("businessType"),revision,restoreKeyRule(d.getJSONObject("businessKeyRule")),restoreFields(d.getJSONArray("fieldSchema")),restoreFields(d.getJSONArray("routingFacts")),restoreFields(d.getJSONArray("workingDataSchema")),restoreLine(d.getJSONObject("lineItemSchema")),restoreAttachment(d.getJSONObject("attachmentRules")),restoreChange(d.getJSONObject("changePolicy")));}
 public BpmBusinessObjectDraft upgradeV1(String contractKey,String objectName,String description,long revision,String canonical){var d=JSON.parseObject(canonical);if(d==null)d=new com.alibaba.fastjson.JSONObject();String sourceSystem=StringUtils.defaultIfBlank(d.getString("sourceSystem"),"LEGACY");String businessType=StringUtils.defaultIfBlank(d.getString("businessType"),contractKey.toUpperCase(Locale.ROOT));var legacyFields=d.getJSONArray("fieldSchema");if(legacyFields==null)legacyFields=d.getJSONArray("fields");return new BpmBusinessObjectDraft(contractKey,objectName,description,sourceSystem,businessType,revision,new BusinessKeyRule(contractKey.toUpperCase(Locale.ROOT),"yyyyMMdd",4),restoreFields(legacyFields),restoreFields(d.getJSONArray("routingFacts")),restoreFields(d.getJSONArray("workingDataSchema")),null,restoreAttachment(d.getJSONObject("attachmentRules")),restoreChange(d.getJSONObject("changePolicy")));}

 private void validate(BpmBusinessObjectDraft draft,List<BusinessObjectValidationFinding> findings){if(draft==null||StringUtils.isBlank(draft.contractKey())||StringUtils.isBlank(draft.objectName())){add(findings,"basic","业务对象名称和编码不能为空");return;}Set<String> keys=new HashSet<>();validateFields(draft.fieldSchema(),"fieldSchema",keys,findings);validateFields(draft.routingFacts(),"routingFacts",keys,findings);validateFields(draft.workingDataSchema(),"workingDataSchema",keys,findings);if(draft.lineItemSchema()!=null){if(draft.lineItemSchema().minRows()==null||draft.lineItemSchema().maxRows()==null||draft.lineItemSchema().minRows()<0||draft.lineItemSchema().maxRows()<draft.lineItemSchema().minRows()||draft.lineItemSchema().maxRows()>200)add(findings,"lineItemSchema.maxRows","明细行数范围不合法");validateFields(draft.lineItemSchema().fields(),"lineItemSchema.fields",new HashSet<>(),findings);}if(draft.attachmentRule()==null||draft.attachmentRule().maxCount()==null||draft.attachmentRule().maxCount()<0||draft.attachmentRule().maxCount()>50)add(findings,"attachmentRule.maxCount","附件数量必须在 0 到 50 之间");if(draft.dataChangeRule()!=null&&"FIELD_CONTROLLED".equals(draft.dataChangeRule().mode())){Set<String> working=draft.workingDataSchema()==null?Set.of():draft.workingDataSchema().stream().map(BusinessObjectField::key).collect(java.util.stream.Collectors.toSet());for(String key:draft.dataChangeRule().editableFields())if(!working.contains(key))add(findings,"dataChangeRule.editableFields","审批可编辑字段不属于审批过程数据："+key);}}
 private void validateFields(List<BusinessObjectField> fields,String path,Set<String> keys,List<BusinessObjectValidationFinding> findings){if(fields==null)return;for(int i=0;i<fields.size();i++){BusinessObjectField field=fields.get(i);String p=path+"["+i+"]";if(field==null||StringUtils.isBlank(field.key())||!keys.add(field.key())){add(findings,p+".key","字段编码为空或跨分区重复");continue;}if(!TYPES.contains(field.type()))add(findings,p+".type","字段类型不受支持");if(field.presentation()==null||!CONTROLS.getOrDefault(field.type(),Set.of()).contains(field.presentation().control()))add(findings,p+".presentation.control","字段类型与控件不匹配");if(field.candidateUsable()&&!"EMPLOYEE_ID".equals(field.type()))add(findings,p+".candidateUsable","只有员工字段可以用于审批人解析");}}
 private void add(List<BusinessObjectValidationFinding> findings,String path,String message){findings.add(new BusinessObjectValidationFinding("BUSINESS_OBJECT_INVALID","BLOCKING",path,message,"请修改该字段后重新校验"));}
 private Map<String,Object> build(BpmBusinessObjectDraft draft){Map<String,Object> d=new LinkedHashMap<>();d.put("schemaVersion",2);d.put("sourceSystem",draft.sourceSystem());d.put("businessType",draft.businessType());d.put("businessKeyRule",keyRule(draft.businessKeyRule()));d.put("fieldSchema",fields(draft.fieldSchema()));d.put("routingFacts",fields(draft.routingFacts()));d.put("workingDataSchema",fields(draft.workingDataSchema()));if(draft.lineItemSchema()!=null)d.put("lineItemSchema",Map.of("name",draft.lineItemSchema().name(),"minRows",draft.lineItemSchema().minRows(),"maxRows",draft.lineItemSchema().maxRows(),"fields",fields(draft.lineItemSchema().fields())));d.put("attachmentRules",attachment(draft.attachmentRule()));d.put("detailLayout",Map.of("sections",new ArrayList<>(List.of("fields","lineItems","attachments"))));d.put("changePolicy",Map.of("mode",draft.dataChangeRule().mode(),"editableFields",new ArrayList<>(draft.dataChangeRule().editableFields())));return d;}
 private Map<String,Object> keyRule(BusinessKeyRule rule){int dateDigits="yyyyMMdd".equals(rule.datePattern())?8:6;return Map.of("prefix",rule.prefix(),"datePattern",rule.datePattern(),"sequenceDigits",rule.sequenceDigits(),"pattern",java.util.regex.Pattern.quote(rule.prefix())+"-[0-9]{"+dateDigits+"}-[0-9]{"+rule.sequenceDigits()+"}");}
 private List<Map<String,Object>> fields(List<BusinessObjectField> fields){if(fields==null||fields.isEmpty())return new ArrayList<>();return fields.stream().map(field->{Map<String,Object> m=new LinkedHashMap<>();m.put("key",field.key());m.put("label",field.label());m.put("type",field.type());m.put("required",field.required());m.put("sensitivity",field.sensitivity());m.put("candidateUsable",field.candidateUsable());m.put("presentation",presentation(field.presentation()));return m;}).collect(java.util.stream.Collectors.toCollection(ArrayList::new));}
 private Map<String,Object> presentation(FieldPresentation p){Map<String,Object> m=new LinkedHashMap<>();m.put("control",p.control());if(p.placeholder()!=null)m.put("placeholder",p.placeholder());if(p.unit()!=null)m.put("unit",p.unit());if(p.options()!=null&&!p.options().isEmpty())m.put("options",p.options());return m;}
 private Map<String,Object> attachment(AttachmentRule r){return Map.of("maxCount",r.maxCount(),"maxSizeMb",r.maxSizeMb(),"allowedExtensions",new ArrayList<>(r.allowedExtensions()),"required",r.required());}
 private BusinessKeyRule restoreKeyRule(com.alibaba.fastjson.JSONObject o){return new BusinessKeyRule(o.getString("prefix"),o.getString("datePattern"),o.getInteger("sequenceDigits"));}
 private List<BusinessObjectField> restoreFields(com.alibaba.fastjson.JSONArray a){if(a==null)return List.of();return a.stream().map(value->{var f=(com.alibaba.fastjson.JSONObject)value;var p=f.getJSONObject("presentation");String type=f.getString("type");FieldPresentation presentation=p==null?defaultPresentation(type):new FieldPresentation(p.getString("control"),p.getString("placeholder"),p.getString("unit"),p.getJSONArray("options")==null?List.of():p.getJSONArray("options").toJavaList(String.class));return new BusinessObjectField(f.getString("key"),StringUtils.defaultIfBlank(f.getString("label"),f.getString("key")),type,f.getBooleanValue("required"),StringUtils.defaultIfBlank(f.getString("sensitivity"),"INTERNAL"),f.getBooleanValue("candidateUsable"),presentation);}).toList();}
 private FieldPresentation defaultPresentation(String type){return new FieldPresentation(switch(type==null?"":type){case "DECIMAL","INTEGER"->"NUMBER";case "BOOLEAN"->"SWITCH";case "DATE"->"DATE";case "DATETIME"->"DATETIME";case "EMPLOYEE_ID"->"EMPLOYEE";default->"INPUT";},null,null,List.of());}
 private LineItemSchema restoreLine(com.alibaba.fastjson.JSONObject o){return o==null?null:new LineItemSchema(o.getString("name"),o.getInteger("minRows"),o.getInteger("maxRows"),restoreFields(o.getJSONArray("fields")));}
 private AttachmentRule restoreAttachment(com.alibaba.fastjson.JSONObject o){return o==null?new AttachmentRule(0,20,List.of(),false):new AttachmentRule(o.getInteger("maxCount"),o.getInteger("maxSizeMb")==null?20:o.getInteger("maxSizeMb"),o.getJSONArray("allowedExtensions")==null?List.of():o.getJSONArray("allowedExtensions").toJavaList(String.class),o.getBooleanValue("required"));}
 private DataChangeRule restoreChange(com.alibaba.fastjson.JSONObject o){return o==null?new DataChangeRule("LOCKED",List.of()):new DataChangeRule(o.getString("mode"),o.getJSONArray("editableFields")==null?List.of():o.getJSONArray("editableFields").toJavaList(String.class));}
}
