package com.hunyuan.sa.bpm.module.integration.service;

import com.baomidou.mybatisplus.core.mapper.BaseMapper; import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.hunyuan.sa.bpm.module.definition.dao.GraphDefinitionVersionDao; import com.hunyuan.sa.bpm.module.integration.dao.*;
import com.hunyuan.sa.bpm.module.integration.domain.entity.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils; import java.time.LocalDateTime; import java.util.List;

@Service
public class BpmM6ConfigurationService {
 private final BpmSourceSystemVersionDao systems; private final BpmSourceApplicationDao apps; private final BpmExternalEmployeeMappingDao mappings;
 private final BpmProcessBindingVersionDao bindings; private final BpmEventSubscriptionVersionDao subscriptions; private final GraphDefinitionVersionDao graphVersions;
 private final BpmConnectorRegistryService connectorRegistry;
 public BpmM6ConfigurationService(BpmSourceSystemVersionDao s,BpmSourceApplicationDao a,BpmExternalEmployeeMappingDao m,BpmProcessBindingVersionDao b,BpmEventSubscriptionVersionDao e,GraphDefinitionVersionDao g,BpmConnectorRegistryService c){systems=s;apps=a;mappings=m;bindings=b;subscriptions=e;graphVersions=g;connectorRegistry=c;}
 public List<BpmSourceSystemVersionEntity> listSystems(){return systems.selectList(Wrappers.<BpmSourceSystemVersionEntity>lambdaQuery().orderByAsc(BpmSourceSystemVersionEntity::getSourceSystemCode).orderByDesc(BpmSourceSystemVersionEntity::getSystemVersion));}
 public List<BpmSourceApplicationEntity> listApplications(){return apps.selectList(Wrappers.<BpmSourceApplicationEntity>lambdaQuery().orderByAsc(BpmSourceApplicationEntity::getSourceSystemCode,BpmSourceApplicationEntity::getApplicationCode));}
 public List<BpmExternalEmployeeMappingEntity> listMappings(){return mappings.selectList(Wrappers.<BpmExternalEmployeeMappingEntity>lambdaQuery().orderByAsc(BpmExternalEmployeeMappingEntity::getSourceSystemCode,BpmExternalEmployeeMappingEntity::getExternalEmployeeId));}
 public List<BpmProcessBindingVersionEntity> listBindings(){return bindings.selectList(Wrappers.<BpmProcessBindingVersionEntity>lambdaQuery().orderByAsc(BpmProcessBindingVersionEntity::getBusinessType).orderByDesc(BpmProcessBindingVersionEntity::getBindingVersion));}
 public List<BpmEventSubscriptionVersionEntity> listSubscriptions(){return subscriptions.selectList(Wrappers.<BpmEventSubscriptionVersionEntity>lambdaQuery().orderByAsc(BpmEventSubscriptionVersionEntity::getBusinessType).orderByDesc(BpmEventSubscriptionVersionEntity::getSubscriptionVersion));}
 @Transactional public Long saveSystem(BpmSourceSystemVersionEntity e){requireDraft(e.getSourceSystemVersionId(),systems,"来源系统");requireText(e.getSourceSystemCode(),"来源系统编码");requireText(e.getSystemName(),"来源系统名称");e.setStatus("DRAFT");return save(systems,e,e.getSourceSystemVersionId());}
 @Transactional public Long publishSystem(Long id){BpmSourceSystemVersionEntity e=require(id,systems,"来源系统");if(!"DRAFT".equals(e.getStatus()))throw new IllegalStateException("只有草稿来源系统可发布");BpmSourceSystemVersionEntity u=new BpmSourceSystemVersionEntity();u.setSourceSystemVersionId(id);u.setStatus("PUBLISHED");u.setPublishedAt(LocalDateTime.now());systems.updateById(u);return id;}
 @Transactional public Long saveApplication(BpmSourceApplicationEntity e){requireText(e.getApplicationCode(),"应用编码");requireText(e.getSourceSystemCode(),"来源系统编码");if(!StringUtils.hasText(e.getSecretRef())||!e.getSecretRef().startsWith("env:"))throw new IllegalArgumentException("应用密钥必须使用 env: 引用");if(e.getStatus()==null)e.setStatus("DISABLED");return save(apps,e,e.getApplicationId());}
 @Transactional public Long saveMapping(BpmExternalEmployeeMappingEntity e){requireText(e.getSourceSystemCode(),"来源系统编码");requireText(e.getExternalEmployeeId(),"外部员工ID");if(e.getHunyuanEmployeeId()==null)throw new IllegalArgumentException("Hunyuan员工ID不能为空");if(e.getStatus()==null)e.setStatus("ACTIVE");return save(mappings,e,e.getMappingId());}
 @Transactional public Long saveBinding(BpmProcessBindingVersionEntity e){requireDraft(e.getBindingVersionId(),bindings,"流程绑定");requireText(e.getBindingKey(),"绑定编码");requireText(e.getBusinessType(),"业务类型");e.setStatus("DRAFT");return save(bindings,e,e.getBindingVersionId());}
 @Transactional public Long publishBinding(Long id){BpmProcessBindingVersionEntity e=require(id,bindings,"流程绑定");if(!"DRAFT".equals(e.getStatus()))throw new IllegalStateException("只有草稿流程绑定可发布");var graph=graphVersions.selectById(e.getGraphDefinitionVersionId());if(graph==null||!"ACTIVE".equals(graph.getLifecycleState()))throw new IllegalStateException("流程绑定引用的 Graph 版本未启用");var query=Wrappers.<BpmProcessBindingVersionEntity>lambdaQuery().eq(BpmProcessBindingVersionEntity::getBusinessType,e.getBusinessType()).eq(BpmProcessBindingVersionEntity::getPriority,e.getPriority()).eq(BpmProcessBindingVersionEntity::getStatus,"PUBLISHED");if(e.getOrganizationId()==null)query.isNull(BpmProcessBindingVersionEntity::getOrganizationId);else query.eq(BpmProcessBindingVersionEntity::getOrganizationId,e.getOrganizationId());if(!StringUtils.hasText(e.getScenario()))query.and(q->q.isNull(BpmProcessBindingVersionEntity::getScenario).or().eq(BpmProcessBindingVersionEntity::getScenario,""));else query.eq(BpmProcessBindingVersionEntity::getScenario,e.getScenario());if(bindings.selectCount(query)>0)throw new IllegalStateException("存在同范围同优先级的已发布流程绑定");BpmProcessBindingVersionEntity u=new BpmProcessBindingVersionEntity();u.setBindingVersionId(id);u.setStatus("PUBLISHED");u.setPublishedAt(LocalDateTime.now());bindings.updateById(u);return id;}
 @Transactional public Long saveSubscription(BpmEventSubscriptionVersionEntity e){requireDraft(e.getSubscriptionVersionId(),subscriptions,"事件订阅");requireText(e.getSubscriptionKey(),"订阅编码");requireText(e.getConnectorKey(),"连接器编码");e.setStatus("DRAFT");return save(subscriptions,e,e.getSubscriptionVersionId());}
 @Transactional public Long publishSubscription(Long id){BpmEventSubscriptionVersionEntity e=require(id,subscriptions,"事件订阅");if(!"DRAFT".equals(e.getStatus()))throw new IllegalStateException("只有草稿事件订阅可发布");connectorRegistry.requireOperation(e.getConnectorKey(),e.getConnectorVersion(),e.getEndpointOperation());if(!StringUtils.hasText(e.getSigningSecretRef())||!e.getSigningSecretRef().startsWith("env:"))throw new IllegalStateException("订阅签名密钥必须使用 env: 引用");BpmEventSubscriptionVersionEntity u=new BpmEventSubscriptionVersionEntity();u.setSubscriptionVersionId(id);u.setStatus("PUBLISHED");u.setPublishedAt(LocalDateTime.now());subscriptions.updateById(u);return id;}
 private <T> Long save(BaseMapper<T> dao,T entity,Long id){if(id==null){dao.insert(entity);return entityId(entity);}dao.updateById(entity);return id;}
 private Long entityId(Object e){if(e instanceof BpmSourceSystemVersionEntity v)return v.getSourceSystemVersionId();if(e instanceof BpmSourceApplicationEntity v)return v.getApplicationId();if(e instanceof BpmExternalEmployeeMappingEntity v)return v.getMappingId();if(e instanceof BpmProcessBindingVersionEntity v)return v.getBindingVersionId();if(e instanceof BpmEventSubscriptionVersionEntity v)return v.getSubscriptionVersionId();throw new IllegalArgumentException("不支持的配置实体");}
 private <T> T require(Long id,BaseMapper<T> dao,String name){T e=id==null?null:dao.selectById(id);if(e==null)throw new IllegalArgumentException(name+"不存在");return e;}
 private <T> void requireDraft(Long id,BaseMapper<T> dao,String name){if(id==null)return;T e=require(id,dao,name);try{String state=(String)e.getClass().getMethod("getStatus").invoke(e);if(!"DRAFT".equals(state))throw new IllegalStateException("已发布"+name+"不可原位修改");}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}}
 private void requireText(String v,String name){if(!StringUtils.hasText(v))throw new IllegalArgumentException(name+"不能为空");}
}
